name: partrm
channels:
  - defaults
  - conda-forge
dependencies:
  - cuda-version=12.6
  - omegaconf=2.3.0
  - openssl=3.3.2
  - python=3.8.18
  - pyyaml=6.0.2
  - yaml=0.2.5
  - pip=20.3.3
  - pip:
      - absl-py==2.1.0
      - basicsr==1.4.2
      - coloredlogs==15.0.1
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==2.18.1
      - decorator==5.1.1
      - deprecated==1.2.14
      - diffusers==0.30.0
      - dlib==19.24.6
      - einops==0.8.0
      - future==1.0.0
      - gradio==4.44.0
      - gradio-client==1.3.0
      - grpcio==1.66.1
      - huggingface-hub==0.24.7
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - ipython==8.12.3
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiui==0.2.13
      - lightning-utilities==0.11.8
      - llvmlite==0.41.1
      - lmdb==1.5.1
      - lpips==0.1.4
      - matplotlib==3.7.5
      - networkx==3.0
      - numba==0.58.1
      - numpy==1.24.4
      - onnxruntime==1.19.2
      - onnxruntime-gpu==1.19.2
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.0.3
      - pillow==10.2.0
      - pip==24.3.1
      - plyfile==1.0.3
      - protobuf==5.28.1
      - psutil==6.0.0
      - pytorch-lightning==2.4.0
      - pytorch-msssim==1.0.0
      - rembg==2.0.59
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - segment-anything==1.0
      - semantic-version==2.10.0
      - setuptools==75.3.0
      - shellingham==1.5.4
      - spaces==0.30.4
      - starlette==0.38.5
      - sympy==1.12
      - tensorboard==2.12.0
      - tensorboardx==2.6.2.2
      - tokenizers==0.19.1
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.4.1
      - torchvision==0.19.1
      - torchmetrics==1.5.0
      - tqdm==4.66.5
      - transformers==4.44.2
      - trimesh==4.4.9
      - typing-extensions==4.9.0
      - xformers==0.0.28